
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: https-bbyalcinkaya-github-io-dbyll 
#google_analytics: dbyll
title: ANLAMLI
url: https://bbyalcinkaya.github.io/anlamli
#BASE_PATH: https://bbyalcinkaya.github.io/dbyll/

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ANLAMLI

description: Siirler ve sarki sozleri hakkinda sallama platformu
author:
  name: ANLAMLI
  #email: dbyll@ismaildemirbilek.com
  #github: dbtek
  #twitter: dbtek
  #pinterest: asd123
  #linkedin: asd123
  #bio: Your stylish, minimalist theme!
  #email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
